name: Update localization
permissions:
  contents: write
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
      - 'Vertigo2/vertigo2_Data/StreamingAssets/Localization/V2_localization.csv'

jobs:
  update_localization:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script
        run: php .github/workflows/update_localization.php

      - name: Git push
        run: |
          git config --global user.name 'izayoi256'
          git config --global user.email 'qwert.izayoi@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/izayoi256/vertigo-2-ja.git
          git add "Vertigo 2/vertigo2_Data/StreamingAssets/Localization/V2_localization.csv"
          git diff --staged --quiet || git commit -m 'Updated V2_localization.csv [ci skip]'
          git push
